name: Server CD Pipeline

on:
  push:
    branches: [release]
    paths:
      - 'packages/server/**'
      - '.github/workflows/server-cd.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install yarn
        uses: npm install -g yarn

      - name: Create env File
        run: |
          echo "${{ secrets.SERVER_ENV }}" > ./packages/server/.env

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nanalmoa-was:latest

      # Pull nginx image -> run container
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            /home/${{ secrets.SSH_USERNAME }}/nanalmoa
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nanalmoa-was:latest
            docker compose up -d was
